### ISSUE TITLE
scss 中 image 不能使用绝对路径

### ISSUE THREAD

**Issue by zacksleo** [qiu8310/minapp#64]
```
background-image: url('/images/image.png')
```
或者这样
```
background-image: data('/images/image.png')
```

**Comment by qiu8310** [comment]
不能这样用吧，这样会直接解析绝对地址，不会使用相对地址解析

**Comment by qiu8310** [comment]
如果 `src/images/image.png` 文件存在，并且你在 scss 中使用 
```scss
{
	background-image: url("images/image.png")  /* 注意是相对地址 */
}
```
应该不会报文件不存在吧！？
